version: '3.9'
services:
  api:
    platform: linux/amd64
    image: prisma-monorepo-api
    build:
      context: ./packages/api/
    environment:
      DATABASE_URL: file:/app/dev.db
    volumes:
      - ./packages/api/node_modules/@bnsouzastests/repository/prisma/dev.db:/app/dev.db
    ports:
      - 3333:3333